id: AD809F2D8
title: f5C49
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 16:11:33.502715
  last_modified_at: 2022-05-27 16:11:33.502783
